name: EAS Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - run: sudo apt-get update
      - run: sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev -y
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Build APK locally
        run: pnpm --filter @ac2/app exec eas build --profile testing --platform android --local --non-interactive --output=app-testing.apk
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: rocca-testing-apk
          path: app-testing.apk
